<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CategoryDrpDwn</name>
   <tag></tag>
   <elementGuidId>8c76f5f3-3716-4949-82fb-21c390e4c06e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jq-selectbox__select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='category_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c6e5d35-fe41-47a8-aa7a-e6e6df5916e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jq-selectbox__select</value>
      <webElementGuid>433cc5c5-9a0b-4d14-bcfc-5af4b93403f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>b5bf07db-afa2-4127-a559-fe9d422ea8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services&quot;)/div[@class=&quot;row filters-row long-select-new&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-7 first-in&quot;]/div[@class=&quot;box-input clearfix&quot;]/div[@class=&quot;cuSelect&quot;]/div[@class=&quot;jq-selectbox jqselect&quot;]/div[@class=&quot;jq-selectbox__select&quot;]</value>
      <webElementGuid>0612fcc1-564c-49ba-a7a3-f1aba6c773ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='services']/div/div/div/div/div/div/div/div</value>
      <webElementGuid>51710cad-84d4-4eb9-bb8a-2df2a40a7ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::div[12]</value>
      <webElementGuid>74443909-00a3-4312-afff-ca5b42dfbd7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/following::div[12]</value>
      <webElementGuid>85929bdb-8ce2-477a-846e-ff4165cc1177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[3]/preceding::div[4]</value>
      <webElementGuid>d9ba3c26-cda2-4310-9965-bfc1795e7a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>2b3fdb5e-31c9-4663-8679-521cb987311b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'All' or . = 'All')]</value>
      <webElementGuid>34a68c57-5775-4eec-975b-4e3648ea01fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
