<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchBtn</name>
   <tag></tag>
   <elementGuidId>887fe6c7-31f5-4b97-8368-6bb1f83be2f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='services']/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>414bb728-a53a-45b2-982e-88c261d1823c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-filter</value>
      <webElementGuid>9828ba85-3bce-4e58-825c-45eb43ae7d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>49325cb9-3fc7-440d-8270-0a62c07716ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services&quot;)/div[@class=&quot;row filters-row long-select-new&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-2 btn-search&quot;]/button[@class=&quot;btn btn-filter&quot;]</value>
      <webElementGuid>774269f0-0820-4e4f-9204-00a2f0a0f8a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='services']/div/div[2]/button</value>
      <webElementGuid>5997d7fb-6aa3-400b-a8d7-71af02c1b0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ 20 km'])[2]/following::button[1]</value>
      <webElementGuid>e0a36859-2113-4d65-9db8-79d7851a017b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ 10 km'])[2]/following::button[1]</value>
      <webElementGuid>1510c89d-7b03-42bf-95f3-8884708f14b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>ef19b6d1-ee8a-455a-8e27-ea8cd686ebc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>dee5f26c-27ff-408a-a27a-42267ead1348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
