<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SEARCH</name>
   <tag></tag>
   <elementGuidId>49ffe60e-0997-4462-a6e7-f5611b3ff383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-filter > span.help</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='services']/div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f83654f-8c64-4bd8-ab3b-38d1e8e1cc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help</value>
      <webElementGuid>3d1bbdea-7601-4a5e-a7ec-62d3e94a4294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>213a0ed7-978e-493b-8e64-2f8618841869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services&quot;)/div[@class=&quot;row filters-row long-select-new&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-2 btn-search&quot;]/button[@class=&quot;btn btn-filter&quot;]/span[@class=&quot;help&quot;]</value>
      <webElementGuid>6087dbff-b50c-4755-9d4c-0b3778622e91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='services']/div/div[2]/button/span</value>
      <webElementGuid>2f36792b-5a3a-4e0b-a64c-3ea743e8945b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ 20 km'])[2]/following::span[1]</value>
      <webElementGuid>804f0c95-f63a-40dc-ab27-868ba5bf722b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ 10 km'])[2]/following::span[1]</value>
      <webElementGuid>9c778239-e230-4a24-a19a-f514300c53c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SORT BY'])[1]/preceding::span[1]</value>
      <webElementGuid>0e1bfdf3-17f1-4ee2-86f6-abd36f61a93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>21b81a5e-0b04-42f1-bbae-27779b91765f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>387a8689-2cb0-4c10-b8c9-48e43e294121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>f0ee7834-e150-4129-ac5a-e08713c0de5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
